version: "3"

services:

  ####################### Frontend Definition #######################
  frontend:
    image: bcros_frontend
    container_name: bcros_frontend
    build:
      context: coops-ui
    command: ["npm", "run", "serve"]
    volumes:
      - ./coops-ui/src:/opt/app/src
      - ./coops-ui/tests:/opt/app/tests
      - ./coops-ui/public:/opt/app/public
    ports:
      - 8080:8080
#    depends_on:
#      - backend
    env_file: ./coops-ui/.env
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - bcros
  ####################### Caddy Definition #######################
  caddy_proxy:
    image: bcros_proxy
    container_name: bcros_proxy
    build:
      context: Caddy
    ports:
      - 2015:2015
    networks:
      - bcros
####################### Legal API Definition #######################
  legal_api:
    image: legal_api
    container_name: legal_api
    build:
      context: legal-api
    env_file:
      - ./legal-api/.env
    ports:
      - 5000:5000
    networks:
      - bcros

####################### Lear Database Definition #######################
  legal_db:
    image: legal_db
    container_name: legal_db
    build:
      context: lear-db
    env_file:
      - ./legal-api/env-wf
    ports:
      - 5432:5432
    networks:
      - bcros

####################### Networks Definition #######################
networks:
  bcros:
    driver: "bridge"

####################### Volumes Definition #######################
volumes:
  postgres-data:
