# Copyright 2020 The Province of British Columbia
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  annotations:
    description: |
      The Network Security Policies (NSP) for the associated
      Platform Services image builds mechanics.
  name: lear-tools-nsp
objects:
  - apiVersion: security.devops.gov.bc.ca/v1alpha1
    kind: ExternalNetwork
    metadata:
      # This metadata field will be what you see with the command
      # `oc get externalnetwork` or `kubctl get externalnetwork`.
      name: all-things-external
      labels:
        app: lear
    spec:
      # This name will be used internally by Aporeto; it should match
      # the `name` field in metadata above.
      description: |
        specify a custom external network that can be
        referenced by name.
      entries:
        - 0.0.0.0/0
      servicePorts:
        - "tcp/80"
        - "tcp/443"

  - apiVersion: security.devops.gov.bc.ca/v1alpha1
    kind: NetworkSecurityPolicy
    metadata:
      name: builder-to-internet
      labels:
        app: lear
    spec:
      description: |
        allow the builder pods to communicate with the internet.
      source:
        - - $namespace=${NAMESPACE}
          - '@app:k8s:serviceaccountname=builder'
      destination:
        - - 'ext:name=all-things-external'

  - apiVersion: security.devops.gov.bc.ca/v1alpha1
    kind: NetworkSecurityPolicy
    metadata:
      name: jenkins-to-internet
      labels:
        app: lear
    spec:
      description: |
        allow the jenkins pods to communicate with the internet.
      source:
        - - $namespace=${NAMESPACE}
          - name=jenkins
      destination:
        - - 'ext:name=all-things-external'

  - apiVersion: security.devops.gov.bc.ca/v1alpha1
    kind: NetworkSecurityPolicy
    metadata:
      name: jenkins-to-tools
      labels:
        app: lear
    spec:
      description: |
        allow the jenkins pods to communicate with other pods.
      source:
        - - $namespace=${NAMESPACE}
          - name=jenkins
      destination:
        - - $namespace=${NAMESPACE}
parameters:
  - name: NAMESPACE
    description: |
      The the name of the namespace the policy is being
      deployed to.
    required: true
    value: cc892f-tools
