name: Business Auth CI

on:
  pull_request:
    types: [assigned, synchronize]
    paths:
      - "queue_services/entity-auth/**"
      - "queue_services/common/**"
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./queue_services/entity-auth

jobs:
  business-auth-ci:
    uses: bcgov/bcregistry-sre/.github/workflows/api-ci.yaml@main
    with:
      app_name: "business-auth"
      working_directory: "./queue_services/entity-auth"
      codecov_flag: "entityauth"