name: Business BN CI

on:
  pull_request:
    types: [assigned, synchronize]
    paths:
      - "queue_services/entity-bn/**"
      - "queue_services/common/**"
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./queue_services/entity-bn

jobs:
  business-bn-ci:
    uses: bcgov/bcregistry-sre/.github/workflows/bn-ci.yaml@main
    with:
      app_name: "business-bn"
      working_directory: "./queue_services/entity-bn"
      codecov_flag: "entitybn"
