name: GCP Filings Notebook Report CI
#Note job will fail tests as a default db is not setup
on:
  push:
    branches:
      - main
    paths:
      - "gcp-jobs/filings-notebook-report/**"
  workflow_dispatch:
    inputs:
      app_name:
        required: true
        type: string
        default: "filings-notebook-report"
      working_directory:
        type: string
        default: ".gcp-jobs/filings-notebook-report"
      codecov_flag:
        type: string
      skip_isort:
        type: string
        default: "false"
      skip_black:
        type: string
        default: "false"

jobs:
  setup:
    # Only allow run the CD flow in protected branch
    if: github.ref_protected == true

    runs-on: ubuntu-24.04

    defaults:
      run:
        shell: bash

    steps:
      # Checkout code
      - name: CI
        uses: bcgov/bcregistry-sre/.github/workflows/backend-ci.yaml@main
        with:
          app_name: ${{ inputs.app_name }}
          working_directory: ${{ inputs.working_directory }}