name: GCP Filings Notebook Report CI

on:
  pull_request:
    types: [assigned, synchronize]
    paths:
      - "gcp-jobs/update-legal-filings/**"
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: ./gcp-jobs/update-legal-filings

jobs:
  furnishings-ci:
    uses: bcgov/bcregistry-sre/.github/workflows/backend-ci.yaml@main
    with:
      app_name: "update-legal-filings"
      working_directory: "./gcp-jobs/update-legal-filings"
      codecov_flag: "update-legal-filings"
